// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lufedzceyxlfdowheubi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx1ZmVkemNleXhsZmRvd2hldWJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAzNTQ1MjcsImV4cCI6MjA1NTkzMDUyN30.hU4f61AbKzBSTaqvdvotCrPKcVykQWav9j8tUg7F4Gw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);